version: '2'

services:
  server:
    image: 'jetbrains/teamcity-server' # the official JetBrains image
    volumes:
      - '/Users/maltehildebrand/projects/teamcity/data:/data/teamcity_server/datadir'
      - '/Users/maltehildebrand/projects/teamcity/log:/data/teamcity/logs'
    ports:
      - 8111:8111
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
  agent:
    image: 'jetbrains/teamcity-minimal-agent' #the official JetBrains image
    environment:
      - SERVER_URL=server:8111